# modal app config
MODAL_CPU = 4.0
MODAL_MEMORY = 32768
MODAL_CONTAINER_IDLE_TIMEOUT = 240

OPENAI_MODEL = "gpt-4-turbo"
OPENAI_MODEL_TEMPERATURE = 0.1

PPLX_MODEL = "sonar-small-online"
PPLX_MODEL_TEMPERATURE = 0.5
