name: biometrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      MODAL_VOLUME: ${{ secrets.MODAL_VOLUME }}
      TERRA_API_KEY: ${{ secrets.TERRA_API_KEY }}
      TERRA_DEV_ID: ${{ secrets.TERRA_DEV_ID }}
      TERRA_SECRET: ${{ secrets.TERRA_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - run: |
          pip install terra-python jsonpath-ng sqlite_utils pandas

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal

      - name: Refresh biometric data
        run: |
          python biometrics.py
          modal volume put --force $MODAL_VOLUME biometric_data.csv  /data/
