name: modal

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.SUGAM_MODAL_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.SUGAM_MODAL_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal


      - name: Deploy job
        run: |
          modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
          modal deploy app.py
